version: '3.9'

services:
  api:
    container_name: digitalword_api
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    volumes:
      - .:/app
    x-develop:
      watch:
        - action: sync
          path: ./
          target: app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    # depends_on:
    #   db:
    #     condition: service_healthy
    command: npm run dev

  # db:
  #   container_name: digitalword_db
  #   image: postgres:14
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
